### ISSUE TITLE
デプロイ時の使用データベースについて

### ISSUE THREAD

**Issue by atomEnvSaver** [osamu38/node-express-socketio-sample#1]
#Herokuにデプロイ時、MySQLのままで動作させることは可能なのでしょうか？
実際、デプロイして動作させるとDBのハンドラ部分でエラーが発生します。
ログを見るとデータ（rows）がundefnedと言うことなんですが
どう回避させればいいかわからず困っています

ローカルではMySQLでの組合せで問題なく動作するのですが

↑↑↑↑

設定の間違いでした。全く違うDBのconnectionになってしまってました。
問題なく動作します。くだらないことですみません。

**Comment by YoshioKimura** [comment]
一つご相談です。こちらのexpressの記事をそのままやらせていただきまして、
最期の画像をアップロードする所で以下のようなエラーが出ました。
Error: Cannot find module 'cloudinary'

[nodemon] app crashed - waiting for file changes before starting...
サーバーがすでに動いているよ、という意味ということらしいのですが、心当たりがあれば解決のための検索ワードや参考にすると良い情報があれば教えて頂けると助かります。

**Comment by osamu38** [comment]
ご指摘ありがとうございます。

`Error: Cannot find module 'cloudinary'`

cloudinaryというmoduleが見つからないとあるので、

```
$ npm install --save cloudinary
```

このコマンドを実行すれば動くと思います。ドキュメントにも追加しました。

**Comment by YoshioKimura** [comment]
ありがとうございます！動きました。あと3週します！
